DROP VIEW IF EXISTS vw_sales_summary CASCADE;
DROP VIEW IF EXISTS vw_shift_fill CASCADE;

DROP TABLE IF EXISTS sale CASCADE;
DROP TABLE IF EXISTS shift_signup CASCADE;
DROP TABLE IF EXISTS shift CASCADE;
DROP TABLE IF EXISTS drink CASCADE;
DROP TABLE IF EXISTS volunteer CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;

DROP TYPE IF EXISTS signup_status CASCADE;
DROP TYPE IF EXISTS drink_category CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
